### ISSUE TITLE
교수님, 질문입니다. 

### ISSUE THREAD

**Issue by leafbird** [zeliard/Dispatcher#6]
프로그램이 실행중일 때, 하나의 실행기(코드상으로는 AsyncExecutable 의 한 인스턴스) 안에서 수행중인 어떤 Job이 있다고 가정합니다. 근데 이 Job의 내용 중에 다른 실행기 인스턴스로 async job을 queueing해야 하는 상황입니다. 
이 때 만약 새 job이 queueing되는 두 번째 실행기를 다른 스레드가 점유하고 처리중이었다면, 단순하게 큐에만 쌓아놓고 되돌아오겠지만, 그렇지 않고 큐가 비어 있었다면 이 실행기는 대기 상태가 됩니다. queueing시킨 스레드가 현재 점유중인 첫번째 실행기를 모두 처리하고 나면 잠시 대기시켜 두었던 두 번째 실행기에 대한 처리를 하게 됩니다.

이를 위해 ThreadLocal.h에는 LExecuterList라는 FIFO 자료구조가 존재하고 있습니다. 

``` cpp
extern thread_local ExecuterListType*   LExecuterList;
```

이제 질문인데요. 
LExecuterList를 스레드 로컬로 설정하신 이유가 있으신가요?
그렇지 않고 대기중인 실행기 리스트를 글로벌 싱글턴으로 만들어서(MPMC로 동작해야겠지요)
여유가 있는 다른 스레드가 좀 더 빨리 대기상태의 실행기를 가져가 처리할 수 있게 구성해도 되지 않을까요?

그리고 두 번째 질문입니다만,
언제 박일님이랑 같이 해서 점심식사 한 번 어떠신지요? ㅎ

**Comment by zeliard** [comment]
ㅎㅎ 올만입니다.
1. 말씀하신대로 LExecuterList를 스레드로컬로 두지 않고 MPMC의 형태의 큐로 두고 처리해도 됩니다! (잘 보셨습니다 ㅎㅎ) MPMC로 하지 않은 이유는 LOCK-FREE MPMC큐를 만들기가 상당히 복잡하기 때문입니다. 반면에 MPSC형태로는 간단하고요.. (물론, 현재 PPL이나 부스트의 LOCK-FREE큐는 MPMC형태입니다. 소스 코드 보시면 아시겠지만 상당히 복잡합니다 ^^)
요약하면, 말씀하신대로 MPMC 형태로 글로벌 실행기 리스트를 만들고 각 워커 스레드에서 WORK-STEALING을 해서 가져가서 처리해도 됩니다. ^^
 
2. 점심이야 캐주얼하게 언제든 좋습니다! 하루 전에만 알려주시면 됩니다^^
